# HTTP Configuration
quarkus.http.port=8081

# CORS Configuration
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173,http://localhost:8090
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-max-age=24H
quarkus.http.cors.access-control-allow-credentials=true

# PocketBase Configuration
pocketbase.url=http://localhost:8090
pocketbase.api.url=${pocketbase.url}/api
quarkus.rest-client."br.com.javaflix.client.PocketBaseClient".url=${pocketbase.api.url}

# JWT Configuration
mp.jwt.verify.publickey.location=${pocketbase.url}/api/collections/users/auth-methods
mp.jwt.verify.issuer=${pocketbase.url}
smallrye.jwt.sign.key.location=privateKey.pem

# Logging
quarkus.log.level=INFO
quarkus.log.category."br.com.javaflix".level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

# Dev Services (desabilitar para usar PocketBase externo)
quarkus.devservices.enabled=false
